from datetime import datetime,timedelta
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash
from sqlalchemy import UniqueConstraint,Index
import secrets
db=SQLAlchemy()
def utcnow():return datetime.utcnow()
class Customer(db.Model):id=db.Column(db.Integer,primary_key=True);name=db.Column(db.String(140),nullable=False);slug=db.Column(db.String(90),unique=True,nullable=False);active=db.Column(db.Boolean,default=True)
class User(UserMixin,db.Model):
 id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,nullable=False,index=True);email=db.Column(db.String(180),unique=True,nullable=False);name=db.Column(db.String(120));role=db.Column(db.String(30),default='fleet_viewer');password_hash=db.Column(db.String(255));active=db.Column(db.Boolean,default=True)
 @property
 def is_active(self):return bool(self.active)
 def set_password(self,p):self.password_hash=generate_password_hash(p)
 def check_password(self,p):return check_password_hash(self.password_hash,p)
class Vehicle(db.Model):
 id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,nullable=False,index=True);fleet_no=db.Column(db.String(50),nullable=False);registration=db.Column(db.String(40));vin=db.Column(db.String(80));make=db.Column(db.String(80));model=db.Column(db.String(80));vehicle_class=db.Column(db.String(40),default='TRUCK');tank_capacity_l=db.Column(db.Float);speed_limit_kmh=db.Column(db.Float,default=80);status=db.Column(db.String(30),default='ACTIVE');created_at=db.Column(db.DateTime,default=utcnow)
 __table_args__=(UniqueConstraint('customer_id','fleet_no'),UniqueConstraint('customer_id','registration'))
class Driver(db.Model):id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,nullable=False,index=True);employee_no=db.Column(db.String(50),nullable=False);name=db.Column(db.String(120),nullable=False);phone=db.Column(db.String(40));licence_code=db.Column(db.String(30));active=db.Column(db.Boolean,default=True)
class DriverAssignment(db.Model):id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,nullable=False,index=True);vehicle_id=db.Column(db.Integer,db.ForeignKey('vehicle.id'));driver_id=db.Column(db.Integer,db.ForeignKey('driver.id'));started_at=db.Column(db.DateTime,default=utcnow);ended_at=db.Column(db.DateTime);vehicle=db.relationship('Vehicle');driver=db.relationship('Driver')
class Device(db.Model):
 id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,nullable=False,index=True);device_uid=db.Column(db.String(100),nullable=False);vehicle_id=db.Column(db.Integer,db.ForeignKey('vehicle.id'));device_type=db.Column(db.String(60));token_hash=db.Column(db.String(255));capabilities=db.Column(db.JSON,default=dict);firmware=db.Column(db.String(60));last_seen=db.Column(db.DateTime);enabled=db.Column(db.Boolean,default=True);vehicle=db.relationship('Vehicle')
 __table_args__=(UniqueConstraint('customer_id','device_uid'),)
 def issue_token(self):raw=secrets.token_urlsafe(42);self.token_hash=generate_password_hash(raw);return raw
 def verify_token(self,raw):return bool(self.token_hash and check_password_hash(self.token_hash,raw))
class Location(db.Model):
 id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,nullable=False,index=True);vehicle_id=db.Column(db.Integer,db.ForeignKey('vehicle.id'),nullable=False,index=True);device_id=db.Column(db.Integer,db.ForeignKey('device.id'),nullable=False);sequence=db.Column(db.String(110),nullable=False);sampled_at=db.Column(db.DateTime,nullable=False,index=True);latitude=db.Column(db.Float,nullable=False);longitude=db.Column(db.Float,nullable=False);accuracy_m=db.Column(db.Float);speed_kmh=db.Column(db.Float);ignition=db.Column(db.Boolean);heading_deg=db.Column(db.Float);quality=db.Column(db.String(20),default='GOOD')
 __table_args__=(UniqueConstraint('device_id','sequence'),Index('ix_location_vehicle_time','vehicle_id','sampled_at'))
class StopEvent(db.Model):id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,index=True);vehicle_id=db.Column(db.Integer,index=True);started_at=db.Column(db.DateTime);ended_at=db.Column(db.DateTime);duration_seconds=db.Column(db.Integer);reason=db.Column(db.String(80),default='NOT CONFIRMED')
class SpeedEvent(db.Model):id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,index=True);vehicle_id=db.Column(db.Integer,index=True);started_at=db.Column(db.DateTime);ended_at=db.Column(db.DateTime);threshold_kmh=db.Column(db.Float);max_speed_kmh=db.Column(db.Float);duration_seconds=db.Column(db.Integer);state=db.Column(db.String(30),default='OPEN')
class FuelObservation(db.Model):id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,index=True);vehicle_id=db.Column(db.Integer,index=True);device_id=db.Column(db.Integer);sampled_at=db.Column(db.DateTime,default=utcnow);litres=db.Column(db.Float);percent=db.Column(db.Float);quality=db.Column(db.String(20),default='GOOD')
class SecurityEvent(db.Model):id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,index=True);vehicle_id=db.Column(db.Integer,db.ForeignKey('vehicle.id'));event_type=db.Column(db.String(160));severity=db.Column(db.String(20),default='WARNING');state=db.Column(db.String(30),default='OPEN');detail=db.Column(db.JSON,default=dict);created_at=db.Column(db.DateTime,default=utcnow);resolution=db.Column(db.Text);vehicle=db.relationship('Vehicle')
class AuditEvent(db.Model):id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,index=True);user_id=db.Column(db.Integer);action=db.Column(db.String(120));entity_type=db.Column(db.String(60));entity_id=db.Column(db.String(60));detail=db.Column(db.JSON,default=dict);created_at=db.Column(db.DateTime,default=utcnow)




class AcceptanceCampaign(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,nullable=False,index=True); name=db.Column(db.String(160),nullable=False); release_name=db.Column(db.String(80),default='Production Release'); environment=db.Column(db.String(40),default='STAGING'); state=db.Column(db.String(30),default='DRAFT'); target_start=db.Column(db.DateTime); target_end=db.Column(db.DateTime); approved_by=db.Column(db.Integer); approved_at=db.Column(db.DateTime); rejection_reason=db.Column(db.Text); created_by=db.Column(db.Integer); created_at=db.Column(db.DateTime,default=utcnow)
class AcceptanceItem(db.Model):
    id=db.Column(db.Integer,primary_key=True); campaign_id=db.Column(db.Integer,db.ForeignKey('acceptance_campaign.id'),nullable=False,index=True); category=db.Column(db.String(60),nullable=False); code=db.Column(db.String(80),nullable=False); title=db.Column(db.String(220),nullable=False); description=db.Column(db.Text); required=db.Column(db.Boolean,default=True); blocking=db.Column(db.Boolean,default=True); state=db.Column(db.String(30),default='NOT_TESTED'); evidence_reference=db.Column(db.String(500)); evidence_note=db.Column(db.Text); executed_by=db.Column(db.Integer); executed_at=db.Column(db.DateTime); reviewed_by=db.Column(db.Integer); reviewed_at=db.Column(db.DateTime); campaign=db.relationship('AcceptanceCampaign',backref=db.backref('items',lazy=True,cascade='all, delete-orphan'))
    __table_args__=(UniqueConstraint('campaign_id','code'),)
class PilotVehicle(db.Model):
    id=db.Column(db.Integer,primary_key=True); campaign_id=db.Column(db.Integer,nullable=False,index=True); vehicle_id=db.Column(db.Integer,db.ForeignKey('vehicle.id'),nullable=False); device_id=db.Column(db.Integer,db.ForeignKey('device.id'),nullable=False); installation_id=db.Column(db.Integer); planned_hours=db.Column(db.Integer,default=168); completed_hours=db.Column(db.Float,default=0); state=db.Column(db.String(30),default='PLANNED'); incidents=db.Column(db.Integer,default=0); notes=db.Column(db.Text); vehicle=db.relationship('Vehicle');device=db.relationship('Device')
class EnduranceRun(db.Model):
    id=db.Column(db.Integer,primary_key=True); campaign_id=db.Column(db.Integer,index=True); name=db.Column(db.String(160)); target_devices=db.Column(db.Integer); duration_hours=db.Column(db.Float); expected_interval_seconds=db.Column(db.Integer); state=db.Column(db.String(30),default='PLANNED'); started_at=db.Column(db.DateTime); completed_at=db.Column(db.DateTime); messages_expected=db.Column(db.BigInteger,default=0); messages_received=db.Column(db.BigInteger,default=0); duplicates=db.Column(db.BigInteger,default=0); rejected=db.Column(db.BigInteger,default=0); p95_ingest_ms=db.Column(db.Float); worker_failures=db.Column(db.Integer,default=0); acceptance_note=db.Column(db.Text)
class ReleaseDecision(db.Model):
    id=db.Column(db.Integer,primary_key=True); campaign_id=db.Column(db.Integer,nullable=False,index=True); decision=db.Column(db.String(30),nullable=False); decided_by=db.Column(db.Integer,nullable=False); decided_at=db.Column(db.DateTime,default=utcnow); item_total=db.Column(db.Integer); item_passed=db.Column(db.Integer); item_failed=db.Column(db.Integer); item_not_tested=db.Column(db.Integer); blocking_open=db.Column(db.Integer); note=db.Column(db.Text)

class PasswordResetToken(db.Model):
    id=db.Column(db.Integer,primary_key=True); user_id=db.Column(db.Integer,nullable=False,index=True); token_hash=db.Column(db.String(255),nullable=False); expires_at=db.Column(db.DateTime,nullable=False); used_at=db.Column(db.DateTime); created_at=db.Column(db.DateTime,default=utcnow)
class UserSecurityProfile(db.Model):
    id=db.Column(db.Integer,primary_key=True); user_id=db.Column(db.Integer,nullable=False,unique=True,index=True); mfa_secret_encrypted=db.Column(db.Text); mfa_enabled=db.Column(db.Boolean,default=False); recovery_codes_hash=db.Column(db.JSON,default=list); password_changed_at=db.Column(db.DateTime); failed_login_count=db.Column(db.Integer,default=0); locked_until=db.Column(db.DateTime)
class BackupJob(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,index=True); kind=db.Column(db.String(30),default='DATABASE'); state=db.Column(db.String(30),default='PENDING'); destination=db.Column(db.String(500)); filename=db.Column(db.String(240)); size_bytes=db.Column(db.BigInteger); sha256=db.Column(db.String(64)); started_at=db.Column(db.DateTime); completed_at=db.Column(db.DateTime); verified_at=db.Column(db.DateTime); error=db.Column(db.Text); created_by=db.Column(db.Integer); created_at=db.Column(db.DateTime,default=utcnow)
class RestoreTest(db.Model):
    id=db.Column(db.Integer,primary_key=True); backup_job_id=db.Column(db.Integer,nullable=False,index=True); state=db.Column(db.String(30),default='PENDING'); target=db.Column(db.String(500)); row_counts=db.Column(db.JSON,default=dict); started_at=db.Column(db.DateTime); completed_at=db.Column(db.DateTime); error=db.Column(db.Text); tested_by=db.Column(db.Integer)
class ReportRun(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,index=True); report_type=db.Column(db.String(60)); vehicle_id=db.Column(db.Integer); period_start=db.Column(db.DateTime); period_end=db.Column(db.DateTime); format=db.Column(db.String(10),default='CSV'); state=db.Column(db.String(30),default='COMPLETED'); generated_by=db.Column(db.Integer); filename=db.Column(db.String(240)); row_count=db.Column(db.Integer,default=0); created_at=db.Column(db.DateTime,default=utcnow)
class WebhookEndpoint(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,index=True); name=db.Column(db.String(120)); url=db.Column(db.String(500)); event_types=db.Column(db.JSON,default=list); signing_secret_hash=db.Column(db.String(255)); enabled=db.Column(db.Boolean,default=True); created_at=db.Column(db.DateTime,default=utcnow)
class SupportBundle(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,index=True); filename=db.Column(db.String(240)); state=db.Column(db.String(30),default='COMPLETED'); includes_logs=db.Column(db.Boolean,default=True); includes_config=db.Column(db.Boolean,default=True); includes_secrets=db.Column(db.Boolean,default=False); created_by=db.Column(db.Integer); created_at=db.Column(db.DateTime,default=utcnow)

class FuelCalibrationProfile(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,nullable=False,index=True); vehicle_id=db.Column(db.Integer,db.ForeignKey('vehicle.id'),nullable=False,index=True); name=db.Column(db.String(120),nullable=False); sensor_type=db.Column(db.String(40),nullable=False); electrical_min=db.Column(db.Float); electrical_max=db.Column(db.Float); engineering_unit=db.Column(db.String(20),default='V'); tank_capacity_l=db.Column(db.Float,nullable=False); tank_shape=db.Column(db.String(40),default='CUSTOM'); filtering_seconds=db.Column(db.Integer,default=30); deadband_l=db.Column(db.Float,default=2); slosh_suppression=db.Column(db.Boolean,default=True); active=db.Column(db.Boolean,default=False); approved=db.Column(db.Boolean,default=False); approved_by=db.Column(db.Integer); approved_at=db.Column(db.DateTime); created_at=db.Column(db.DateTime,default=utcnow); vehicle=db.relationship('Vehicle')
class FuelCalibrationPoint(db.Model):
    id=db.Column(db.Integer,primary_key=True); profile_id=db.Column(db.Integer,db.ForeignKey('fuel_calibration_profile.id'),nullable=False,index=True); sequence=db.Column(db.Integer,nullable=False); raw_value=db.Column(db.Float,nullable=False); percent=db.Column(db.Float,nullable=False); litres=db.Column(db.Float,nullable=False); note=db.Column(db.String(200)); profile=db.relationship('FuelCalibrationProfile',backref=db.backref('points',lazy=True,cascade='all, delete-orphan'))
    __table_args__=(UniqueConstraint('profile_id','sequence'),)
class AutomotiveInstallationProfile(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,nullable=False,index=True); vehicle_id=db.Column(db.Integer,db.ForeignKey('vehicle.id'),nullable=False,index=True); device_id=db.Column(db.Integer,db.ForeignKey('device.id'),nullable=False,index=True); board_revision=db.Column(db.String(80),nullable=False); interface_revision=db.Column(db.String(80),nullable=False); electrical_system_v=db.Column(db.Integer,nullable=False); ignition_source=db.Column(db.String(120)); engine_run_source=db.Column(db.String(120)); charging_source=db.Column(db.String(120)); supply_voltage_source=db.Column(db.String(120)); fuel_sensor_source=db.Column(db.String(120)); protected_inputs_verified=db.Column(db.Boolean,default=False); outputs_safe_boot_off=db.Column(db.Boolean,default=False); commissioned=db.Column(db.Boolean,default=False); commissioned_by=db.Column(db.Integer); commissioned_at=db.Column(db.DateTime); notes=db.Column(db.Text); created_at=db.Column(db.DateTime,default=utcnow); vehicle=db.relationship('Vehicle');device=db.relationship('Device')
class CommissioningCheck(db.Model):
    id=db.Column(db.Integer,primary_key=True); installation_id=db.Column(db.Integer,db.ForeignKey('automotive_installation_profile.id'),nullable=False,index=True); code=db.Column(db.String(80),nullable=False); label=db.Column(db.String(180),nullable=False); required=db.Column(db.Boolean,default=True); state=db.Column(db.String(20),default='PENDING'); evidence=db.Column(db.Text); checked_by=db.Column(db.Integer); checked_at=db.Column(db.DateTime); installation=db.relationship('AutomotiveInstallationProfile',backref=db.backref('checks',lazy=True,cascade='all, delete-orphan'))
    __table_args__=(UniqueConstraint('installation_id','code'),)
class DataRetentionPolicy(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,nullable=False,unique=True,index=True); location_days=db.Column(db.Integer,default=730); event_days=db.Column(db.Integer,default=2555); audit_days=db.Column(db.Integer,default=2555); fuel_days=db.Column(db.Integer,default=2555); updated_at=db.Column(db.DateTime,default=utcnow,onupdate=utcnow)

class DeviceState(db.Model):
    id=db.Column(db.Integer,primary_key=True); customer_id=db.Column(db.Integer,nullable=False,index=True); device_id=db.Column(db.Integer,db.ForeignKey('device.id'),nullable=False,unique=True,index=True); current_state=db.Column(db.String(30),default='NEVER_SEEN'); previous_state=db.Column(db.String(30)); state_changed_at=db.Column(db.DateTime,default=utcnow); last_evaluated_at=db.Column(db.DateTime); last_alert_at=db.Column(db.DateTime); device=db.relationship('Device')
class WorkerLease(db.Model):
    id=db.Column(db.Integer,primary_key=True); name=db.Column(db.String(80),unique=True,nullable=False); owner=db.Column(db.String(160)); acquired_at=db.Column(db.DateTime); heartbeat_at=db.Column(db.DateTime); expires_at=db.Column(db.DateTime); last_run_started_at=db.Column(db.DateTime); last_run_completed_at=db.Column(db.DateTime); last_error=db.Column(db.Text); processed_count=db.Column(db.Integer,default=0)
class CorrelationRun(db.Model):
    id=db.Column(db.Integer,primary_key=True); worker_name=db.Column(db.String(80)); started_at=db.Column(db.DateTime,default=utcnow); completed_at=db.Column(db.DateTime); state=db.Column(db.String(30),default='RUNNING'); devices_evaluated=db.Column(db.Integer,default=0); events_created=db.Column(db.Integer,default=0); notifications_queued=db.Column(db.Integer,default=0); error=db.Column(db.Text)

class Geofence(db.Model):
 id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,index=True);name=db.Column(db.String(120),nullable=False);kind=db.Column(db.String(30),default='KEEP_IN');latitude=db.Column(db.Float,nullable=False);longitude=db.Column(db.Float,nullable=False);radius_m=db.Column(db.Float,default=500);severity=db.Column(db.String(20),default='WARNING');active=db.Column(db.Boolean,default=True)
 __table_args__=(UniqueConstraint('customer_id','name'),)
class NotificationQueue(db.Model):id=db.Column(db.Integer,primary_key=True);customer_id=db.Column(db.Integer,index=True);event_type=db.Column(db.String(80));event_id=db.Column(db.String(80));channel=db.Column(db.String(30),default='WEBHOOK');destination=db.Column(db.String(500));state=db.Column(db.String(30),default='PENDING');attempt_count=db.Column(db.Integer,default=0);last_error=db.Column(db.Text);created_at=db.Column(db.DateTime,default=utcnow);delivered_at=db.Column(db.DateTime)
def seed_demo():
 if Customer.query.filter_by(slug='private-fleet').first():return
 c=Customer(name='Private Fleet',slug='private-fleet');db.session.add(c);db.session.flush();u=User(customer_id=c.id,email='admin@fleettrack.local',name='Fleet Administrator',role='fleet_admin');u.set_password('ChangeMe123!');db.session.add(u)
 v=Vehicle(customer_id=c.id,fleet_no='TRK-0012',registration='KLM 482 GP',make='Volvo',model='FH',tank_capacity_l=600);db.session.add(v);db.session.flush();d=Device(customer_id=c.id,device_uid='FT360-100',vehicle_id=v.id,device_type='SIM808 / SAMD21',capabilities={'location':True,'fuel_level':True},last_seen=utcnow());d.issue_token();db.session.add(d);db.session.flush()
 for n in range(5):db.session.add(Location(customer_id=c.id,vehicle_id=v.id,device_id=d.id,sequence=f'demo-{n}',sampled_at=utcnow()-timedelta(minutes=4-n),latitude=-26.70+n*.001,longitude=27.82+n*.001,accuracy_m=9,speed_kmh=78,ignition=True))
 db.session.commit()
